package com.kavisoft.web.abclaboratories.util.email;

import java.util.HashMap;

//AppointmentConfirmationEmailTemplate
public class AppointmentDetailsEmailBluePrint implements EmailBluePrint {

	@Override
	public String generateEmailBluePrint(HashMap<String, String> data) {
		// TODO Auto-generated method stub
		return "<!DOCTYPE html>\n"
				+ "<html lang=\"en\">\n"
				+ "\n"
				+ "<head>\n"
				+ "    <meta charset=\"UTF-8\">\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
				+ "    <title>ABC Laboratories - Appointment Confirmation</title>\n"
				+ "    <style>\n"
				+ "        /* Add your CSS styles here */\n"
				+ "        body {\n"
				+ "            font-family: Arial, sans-serif;\n"
				+ "            line-height: 1.6;\n"
				+ "            background-color: #f9f9f9;\n"
				+ "            margin: 0;\n"
				+ "            padding: 0;\n"
				+ "        }\n"
				+ "\n"
				+ "        .container {\n"
				+ "            max-width: 600px;\n"
				+ "            margin: 20px auto;\n"
				+ "            padding: 20px;\n"
				+ "            background: #fff;\n"
				+ "            border-radius: 8px;\n"
				+ "            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
				+ "        }\n"
				+ "\n"
				+ "        .header {\n"
				+ "            background-color: #4caf50;\n"
				+ "            color: #ffffff;\n"
				+ "            text-align: center;\n"
				+ "            padding: 10px 0;\n"
				+ "            border-radius: 8px 8px 0 0;\n"
				+ "        }\n"
				+ "\n"
				+ "        h2 {\n"
				+ "            color: #333;\n"
				+ "            text-align: center;\n"
				+ "        }\n"
				+ "\n"
				+ "        p {\n"
				+ "            margin-bottom: 20px;\n"
				+ "        }\n"
				+ "\n"
				+ "        ul {\n"
				+ "            margin-bottom: 20px;\n"
				+ "            padding-left: 20px;\n"
				+ "        }\n"
				+ "\n"
				+ "        li {\n"
				+ "            margin-bottom: 8px;\n"
				+ "        }\n"
				+ "\n"
				+ "        .footer {\n"
				+ "            background-color: #f4f4f4;\n"
				+ "            border-top: 1px solid #ddd;\n"
				+ "            padding: 10px 20px;\n"
				+ "            border-radius: 0 0 8px 8px;\n"
				+ "        }\n"
				+ "    </style>\n"
				+ "</head>\n"
				+ "\n"
				+ "<body>\n"
				+ "    <div class=\"container\">\n"
				+ "        <div class=\"header\">\n"
				+ "            <h1>ABC Laboratories</h1>\n"
				+ "        </div>\n"
				+ "        <h2>Appointment Confirmation</h2>\n"
				+ "        <p>Dear "
				+ data.get("name")
				+ ",</p>\n"
				+ "        <p>Your appointment with ABC Laboratories has been successfully booked. Below are the details:</p>\n"
				+ "        <ul>\n"
				+ "            <li><strong>Appointment Id:</strong> "+data.get("id")+"</li>\n"
				+ "            <li><strong>Test Type:</strong> "+data.get("type")+"</li>\n"
				+ "            <li><strong>Appointment Date and time :</strong> "+data.get("datetime")+"</li>\n"
				+ "            <li><strong>Branch :</strong> "+data.get("branch")+"</li>\n"
				+ "        </ul>\n"
				+ "        <p>If you have any questions or need to reschedule, please feel free to contact us at:</p>\n"
				+ "        <p>Email: info@abclaboratories.lk</p>\n"
				+ "        <p>Phone: +94 (0)11 123 4567</p>\n"
				+ "        <p>Thank you for choosing ABC Laboratories. We look forward to serving you.</p>\n"
				+ "        <div class=\"footer\">\n"
				+ "            <p>Best regards,<br>ABC Laboratories Team</p>\n"
				+ "        </div>\n"
				+ "    </div>\n"
				+ "</body>\n"
				+ "\n"
				+ "</html>\n"
				+ "";
	}

}
